In [1]:
import numpy as np

from utils import prefix_sum_2d

In [24]:
np.random.seed(42)
d1, d2 = 10, 10
# mask = np.random.choice([0, 1], size=(d1,d2), p=[0.7, 0.3])
mask = np.ones((d1, d2))
mask_prefix_sum = prefix_sum_2d(mask)

n, m = 2, 5
ni = np.cumsum(mask.shape[0] // n * np.ones(n, dtype=int)) - 1
mi =  np.cumsum(mask.shape[1] // m * np.ones(m, dtype=int)) - 1

print(ni, mi)
print(mask)
print(mask_prefix_sum)

[4 9] [1 3 5 7 9]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [  2.   4.   6.   8.  10.  12.  14.  16.  18.  20.]
 [  3.   6.   9.  12.  15.  18.  21.  24.  27.  30.]
 [  4.   8.  12.  16.  20.  24.  28.  32.  36.  40.]
 [  5.  10.  15.  20.  25.  30.  35.  40.  45.  50.]
 [  6.  12.  18.  24.  30.  36.  42.  48.  54.  60.]
 [  7.  14.  21.  28.  35.  42.  49.  56.  63.  70.]
 [  8.  16.  24.  32.  40.  48.  56.  64.  72.  80.]
 [  9.  18.  27.  36.  45.  54.  63.  72.  81.  90.]
 [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]]


In [25]:
for i in range(len(ni)):
    for j in range(len(mi)):
        print( mask_prefix_sum[ni[i], mi[j]])

10.0
20.0
30.0
40.0
50.0
20.0
40.0
60.0
80.0
100.0


In [9]:
ni

5.0